nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:8000', 'http://127.0.0.1:8000']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    allow_credentials: false
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:8000', 'http://127.0.0.1:8000']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
      allow_credentials: false
      max_age: 3600
