nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_credentials: false
        max_age: 3600

    paths:
        '^/':
            allow_origin: ['*']
            allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_credentials: false
            max_age: 3600
